spring.application.name=taskmanager

#H2 DB CONNECTION
spring.datasource.url=jdbc:h2:mem:tasmanagerdb
spring.datasource.driverClassName=org.h2.Driver
spring.datasource.username=sa
spring.datasource.password=RXQSa4202@a
spring.jpa.database-platform=org.hibernate.dialect.H2Dialect
spring.h2.console.enabled=true

#JPA /Hibernate for prod use validate

spring.jpa.hibernate.ddl-auto=update